# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7600cfbc88ca12fd140c7e989b75b71af71ca931a1b1a73280c241562150da37c7d55919193ff730cbb979b3dcd7f9f7a430dedb3b3a42c41d97fd98db97bcf

test:
  secret_key_base: ac0365ab1b7be294d7034fc3bc1dae70e9363bcb2033ca910960f7e91511dde6fcd45aa89bc1d0b649c0f1b05c867ffcf9bd9fda34f82db5926e8a517ac3bfdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
